#! /bin/bash
#
# C H E C K
#
# check last edited Sat Oct  7 15:50:04 2023
#
PROGRAM=ping3
#
# A network device on your local network is the target
#  change this IPv4 Address to suit your circumstances.
TARGET=192.168.1.1
#
# A Microsoft Windows device on your local network
#  change this IPv4 Address to suit your circumstances.
#  If you want a response the Windows firewall may have
#  to be adjusted to allow the ICMP request through.
WINDOWS_TARGET=192.168.1.121
#
# A network device on your local network that responds
# to ICMP NETMASK requests. This may be a macOS system
# which has been set to respond with the command; -
# sudo sysctl net.inet.icmp.maskrepl=1
NETMASK_TARGET=192.168.1.103
#
echo
echo "Operating System designation is $OSTYPE"
echo
#
if [[ "$OSTYPE" == "darwin"* ]] ; then
  PRIV=""
else
  PRIV="sudo"
fi
#
#
LOCAL_INTERFACE=`$PRIV ../$PROGRAM $TARGET -D -c1 | awk '/Destination Address/{print $4}'`
#
# Compare standard ICMP ECHO request pings
#
echo "##############################################"
echo "# 1(a) Test standard ICMP ECHO request pings #"
echo "##############################################"
echo
#
echo "$PRIV ../$PROGRAM $TARGET"
$PRIV ../$PROGRAM  $TARGET
sleep 1
echo
#
echo "ping -c 3 $TARGET"
ping -c 3 $TARGET
sleep 1
echo
#
# Test the IPv4 Header Option Timestamp
# added to a standard ICMP ECHO request ping
# Compare output against standard OS system
# ping if on Linux system
#
echo "###########################################"
echo "# 1(b) Test IPv4 Header Option Timestamps #"
echo "###########################################"
echo
#
echo "$PRIV ../$PROGRAM $TARGET -t0"
$PRIV ../$PROGRAM $TARGET -t0
sleep 1
echo
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
  echo "ping -4 -c 2 -T tsonly $TARGET"
  ping -4 -c 2 -T tsonly $TARGET
  sleep 1
  echo
fi
#
echo "$PRIV ../$PROGRAM $TARGET -t1"
$PRIV ../$PROGRAM $TARGET -t1
sleep 1
echo
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
  echo "ping -4 -c 2 -T tsandaddr $TARGET"
  ping -4 -c 2 -T tsandaddr $TARGET
  sleep 1
  echo
fi
#
echo "$PRIV ../$PROGRAM $TARGET -t3"
$PRIV ../$PROGRAM $TARGET -t3
sleep 1
echo
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
  echo "ping -4 -c 2 -T tsprespec $TARGET $LOCAL_INTERFACE $TARGET" 
  ping -4 -c 2 -T tsprespec $TARGET $LOCAL_INTERFACE $TARGET
  sleep 1
  echo
fi
#
# Test the ICMP TIMESTAMP option and
# compare to ping output if on macOS
#
echo "###################################"
echo "# 2(a) Test ICMP TIMESTAMP option #"
echo "###################################"
echo
#
echo "$PRIV ../$PROGRAM $TARGET -T"
$PRIV ../$PROGRAM $TARGET -T
sleep 1
echo
#
# On macOS the ping utility has the capability to send
# ICMP TIMESTAMP requests, but sudo is needed if the
# "-s 0" is left out of the command line
#
if [[ "$OSTYPE" == "darwin"* ]] ; then
  echo "ping -c 3 -M time -s 0 $TARGET"
  ping -c 3 -M time -s 0 $TARGET
  sleep 1
  echo
fi
#
# Compare output on a Microsoft Windows target
# which by default appears to have little endian
# timestamp replies
#
echo "######################################################"
echo "# 2(b) Test ICMP TIMESTAMP option for Windows target #"
echo "######################################################"
echo
echo "$PRIV ../$PROGRAM $WINDOWS_TARGET -T1"
$PRIV ../$PROGRAM $WINDOWS_TARGET -T1
sleep 1
echo
#
if [[ "$OSTYPE" == "darwin"* ]] ; then
  echo "ping -c 3 -M time -s 0 $WINDOWS_TARGET"
  ping -c 3 -M time -s 0 $WINDOWS_TARGET
  sleep 1
  echo
fi
#
# Test the ICMP NETMASK option and
# compare to ping -M mask output if on macOS
#
echo "###############################"
echo "# 3. Test ICMP NETMASK option #"
echo "###############################"
echo
#
echo "$PRIV ../$PROGRAM $NETMASK_TARGET -M"
$PRIV ../$PROGRAM $NETMASK_TARGET -M
#
# On macOS the ping utility has the capability to send
# ICMP NETMASK requests, but sudo is needed if the
# "-s 0" is left out of the command line
#
if [[ "$OSTYPE" == "darwin"* ]] ; then
sleep 1
echo
  echo "ping -c 3 -M mask -s 0 $NETMASK_TARGET"
  ping -c 3 -M mask -s 0 $NETMASK_TARGET
fi
