#! /bin/bash
#
# C H K
#
# chk last edited Fri Oct 20 20:19:30 2023
#
PROGRAM=ping3
TARGET=www.apple.com
LOCAL_GATEWAY=192.168.1.1
#
echo
echo "Operating System designation is $OSTYPE"
echo
#
if [[ "$OSTYPE" == "darwin"* ]] ; then
  PRIV=""
else
  PRIV=sudo
fi
#
LOCAL_INTERFACE=`$PRIV ../$PROGRAM -D -c1 $LOCAL_GATEWAY | awk '/Destination Address/{print $4}'`
#
# Test standard ICMP ECHO request ping
# Compare output against standard ping if on
# Linux system
#
echo "#########################################"
echo "# Test standard ICMP ECHO request pings #"
echo "#########################################"
echo
#
echo "$PRIV ../$PROGRAM $TARGET"
$PRIV ../$PROGRAM $TARGET
sleep 1
echo
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
  echo "ping -4 -c 3 $TARGET"
  ping -4 -c 3 $TARGET
else
  echo "ping -c 3 $TARGET"
  ping -c 3 $TARGET
fi
sleep 1
echo
#
# Test the IPv4 Header Option Timestamp
# added to a standard ICMP ECHO request ping
# Compare output against standard ping if on
# Linux system
#
echo "###################################################"
echo "# Test verbose IPv4 Header Option Timestamp pings #"
echo "###################################################"
echo
#
echo "$PRIV ../$PROGRAM -T tsonly -v $TARGET"
$PRIV ../$PROGRAM -T tsonly -v $TARGET
sleep 1
echo
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
  echo "ping -4 -c 2 -T tsonly $TARGET"
  ping -4 -c 2 -T tsonly $TARGET
  sleep 1
  echo
fi
#
# Test short cut tsprespec operation, where failure
# to specify the pre-specified devices results
# in the target and the local interface being
# put in as a default.
#
echo "$PRIV ../$PROGRAM -T tsprespec -v $TARGET"
$PRIV ../$PROGRAM -T tsprespec -v $TARGET
sleep 1
echo
#
if [[ "$LOCAL_INTERFACE" != "" ]] ; then  # Test that we have local interface info
  if [[ "$OSTYPE" == "linux-gnu" ]] ; then
    echo "ping -4 -c 2 -T tsprespec $TARGET $LOCAL_INTERFACE $TARGET"
    ping -4 -c 2 -T tsprespec $TARGET $LOCAL_INTERFACE $TARGET
    sleep 1
    echo
  fi
fi
#
# Test the IPv4 Header Option Record Route
# added to a standard ICMP ECHO request ping
# Compare output against standard ping if on
# Linux system
#
echo "######################################################"
echo "# Test verbose IPv4 Header Option Record Route pings #"
echo "######################################################"
echo
#
echo "$PRIV ../$PROGRAM -R -v $TARGET"
$PRIV ../$PROGRAM -R -v $TARGET
#
if [[ "$OSTYPE" == "linux-gnu" ]] ; then
sleep 1
echo
  echo "ping -4 -c 2 -R $TARGET"
  ping -4 -c 2 -R $TARGET
fi
